Switch from internal/logging to log/slog
When Blobby was written there wasn't a really good standard for
structured logging libraries so the internal/logging library was
written and used through the code. Now, a few years later golang
has added log/slog which is a structured logging library that is
good enough, and requires a lot less explaining and maintenance.

This chane switches all of the uses of logging over, which also
necessitated adding context.Context objects to a lot of the method
calls, as wlel as plumbing to pass those values through where that
makes sense. This also uses contexts for cancelation to match the
modern golang style.

diff --git a/scripts/check b/scripts/check
--- a/scripts/check
+++ b/scripts/check
@@ -60,6 +60,12 @@ if ! $opt_quick; then
 	./scripts/build -cq
 fi
 
+printf >&2 'Running: gofmt check.\n'
+if find * -type f -not -name vendor -name \*.go -not -path 'vendor/*' -print0 | xargs -0 gofmt -l | grep . ; then
+	printf >&2 'Files with format errors found.\n'
+	exit 1
+fi
+
 # Rethink this if we have incompatible tags
 printf >&2 'Running: go test ./...\n'
 go test -tags aws ./...
